[tool.poetry]
name = "django-mongoengine"
version = "0.3.3"
description = "Django support for MongoDB via MongoEngine"
authors = ["Ross Lawley <ross.lawley@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
django = ">1.11"
mongoengine = ">=0.14"

[tool.poetry.dev-dependencies]
sphinx = "^2.4.3"
nose = "^1.3.7"
coverage = "^5.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
